import EventEmitter = Phaser.Events.EventEmitter;
export const EventManager = new EventEmitter()

export enum Events {
	END_TURN = 'END_TURN',
	USE_REMAINING_DICE = 'USE_REMAINING_DICE',
	REQUIREMENT_PROGRESS = 'REQUIREMENT_PROGRESS',
	REQUIREMENT_COMPLETED = 'REQUIREMENT_COMPLETED',
	QUEST_COMPLETED = 'QUEST_COMPLETED',
	QUEST_FAILED = 'QUEST_FAILED',
	MAIN_QUEST_PROGRESS = 'MAIN_QUEST_PROGRESS',
	STAGE_COMPLETED = 'STAGE_COMPLETED',
	// LOCK_OPENED = 'LOCK_OPENED',
}
